### ISSUE TITLE
Error 16 UNAUTHENTICATED when invoking Google Cloud Translate

### ISSUE THREAD

**Issue by Jan-Jan** [fkirc/attranslate#242] opened 2022-10-10 19:21 UTC
**Describe the bug**
I get an `UNAUTHENTICATED` error, despite having registered for Google Cloud Translate API and getting a key. I suspect my json file has the wrong structure.

**To Reproduce**
A description of what the bug is. When I attempt to run the script below
```
#!/bin/bash
set -e # abort on errors

# This example translates an english JSON-file into spanish, chinese and german. It uses Google Cloud Translate.
BASE_DIR="static/locales"
SERVICE_ACCOUNT_KEY="gcloud_translation_key.json"
COMMON_ARGS=( "--srcLng=en" "--srcFormat=nested-json" "--targetFormat=nested-json" "--service=google-translate" "--serviceConfig=$SERVICE_ACCOUNT_KEY" )

# install attranslate if it is not installed yet
attranslate --version || npm install -g attranslate

attranslate --srcFile=$BASE_DIR/en/translation.json --targetFile=$BASE_DIR/de/translation.json --targetLng=de "${COMMON_ARGS[@]}"
```
I get the following error
```
1.8.1
Invoke 'google-translate' from 'en' to 'de' with 8 inputs...
An error occurred:
16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: key must be a string, a buffer or an object
Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: key must be a string, a buffer or an object
```
I suspect it is because my `gcloud_translation_key.json` file is malformed
```
{
  "key": "<the key I got from 'Enable APIs and services' on GCloud for translation>",
  "project_id": "<my project id>"
}
```

**Expected behavior**
I expect the translated files to be output.

**Files**
I've added the script and config I use inline.

**Additional context**
Nothing else.

Thank you in advance for your help.

**Comment by fkirc** [comment] 2022-10-11 09:29
Hi,

I do not know the exact problem with the JSON-file, but there is one thing that looks suspicious:

Did you generate the whole JSON-file with Google or did you modify it on your own?
I think that attranslate only works with Google-generated JSON-files that contain a key for a so-called „service account“.

**Comment by fkirc** [comment] 2023-04-17 16:33
I am closing the issue for now, but please feel free to re-open if the issue is still relevant.

**Closed by fkirc** 2023-04-17 16:33 UTC
